author: DerFlash
database: true
description: CNVotifierAddon
main: de.derflash.plugins.cnvote.CNVotifierAddon
name: CNVotifierAddon
startup: postworld
url: http://www.cube-nation.de/
version: '${project.version}'

depend:
  - PluginUtils

commands:
    cnvote:
        description: Test vote
        usage: /cnvote test

permissions:
  cnvotifieraddon.admin:
    description: ...
